version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    groups:
      aws-sdk:
        patterns:
          - github.com/aws/aws-sdk-go-v2
          - github.com/aws/aws-sdk-go-v2/*

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
