AWSTemplateFormatVersion: 2010-09-09
Transform: Mackerel
Description: Mackerel resources

Resources:
  Org:
    Type: Mackerel::Org

  Service:
    Type: Mackerel::Service
    Properties:
      Name: myService

  Role:
    Type: Mackerel::Role
    Properties:
      Service: !Ref Service
      Name: myRole

  Host:
    Type: Mackerel::Host
    Properties:
      Name: myHost
      Roles:
        - !Ref Role

  MonitorConnectivity:
    Type: Mackerel::Monitor
    Properties:
      Type: connectivity
      Name: connectivity
      Memo: memo
      Scopes:
        - !Ref Service
        - !Ref Role
      ExcludeScopes:
        - !Ref Service
        - !Ref Role
      NotificationInterval: 10

  MonitorHost:
    Type: Mackerel::Monitor
    Properties:
      Type: host
      Name: host
      Duration: 1
      Metric: some.metric
      Operator: ">"
      Warning: 2.71828182846
      Critical: 3.14159265359
      MaxCheckAttempts: 10
      Scopes:
        - !Ref Service
        - !Ref Role
      ExcludeScopes:
        - !Ref Service
        - !Ref Role
      NotificationInterval: 10

  MonitorExternal:
    Type: Mackerel::Monitor
    Properties:
      Type: external
      Name: external
      Method: GET
      Url: https://example.com
      RequestBody: ""
      Service: !Ref Service
      NotificationInterval: 60
      ResponseTimeWarning: 5000
      ResponseTimeCritical: 10000
      ResponseTimeDuration: 3
      ContainsString: Example
      MaxCheckAttempts: 3
      CertificationExpirationWarning: 90
      CertificationExpirationCritical: 30
      SkipCertificateVerification: false
      Headers:
        - Name: Cache-Control
          Value: no-cache

  MonitorExpression:
    Type: Mackerel::Monitor
    Properties:
      Type: expression
      Name: expression
      Expression: avg(roleSlots("server:role","loadavg5"))
      Operator: ">"
      Warning: 5.0
      Critical: 10.0
      NotificationInterval: 60

  MonitorAnomalyDetection:
    Type: Mackerel::Monitor
    Properties:
      Type: anomalyDetection
      Name: anomaly detection
      Scopes:
        - !Ref Service
        - !Ref Role
      WarningSensitivity: insensitive
      CriticalSensitivity: normal
      MaxCheckAttempts: 3
      TrainingPeriodFrom: 1573198000
      NotificationInterval: 60

  NotificationChannelEmail:
    Type: Mackerel::NotificationChannel
    Properties:
      Type: email
      Name: email notification
      Emails:
        - john.doe@example.com
      Events:
        - alert
        - alertGroup

  NotificationChannelSlack:
    Type: Mackerel::NotificationChannel
    Properties:
      Type: slack
      Name: slack notification
      Url: https://example.com
      Mentions:
        Ok: it's ok message
        Warning: it's warning message
        Critical: it's critical message
      EnabledGraphImage: true
      Events:
        - alert
        - alertGroup
        - hostStatus
        - hostRegister
        - hostRetire
        - monitor

  NotificationChannelWebHook:
    Type: Mackerel::NotificationChannel
    Properties:
      Type: webhook
      Name: webhook
      Url: https://example.com
      Events:
        - alert
        - alertGroup
        - hostStatus
        - hostRegister
        - hostRetire
        - monitor

  NotificationGroup1:
    Type: Mackerel::NotificationGroup
    Properties:
      Name: notification group1

  NotificationGroup2:
    Type: Mackerel::NotificationGroup
    Properties:
      Name: notification group2
      NotificationLevel: critical
      ChildNotificationGroupIds:
        - !Ref NotificationGroup1
      ChildChannelIds:
        - !Ref NotificationChannelEmail
        - !Ref NotificationChannelSlack
        - !Ref NotificationChannelWebHook
      Monitors:
        - Id: !Ref MonitorConnectivity
          SkipDefault: true
      Services:
        - Id: !Ref Service

  Dashboard:
    Type: Mackerel::Dashboard
    Properties:
      Title: awesome dashboard
      Memo: my memo
      UrlPath: awesome-dashboard
      Widgets:
        - Type: graph
          Title: host graph
          Graph:
            Type: host
            Name: host
            Host: !Ref Host
          Range:
            Type: relative
            Period: 3600
            Offset: 0
          Layout:
            X: 0
            Y: 0
            Width: 24
            Height: 32
        - Type: graph
          Title: role graph
          Graph:
            Type: role
            Role: !Ref Role
            Name: some.metric
            IsStacked: false
          Range:
            Type: relative
            Period: 3600
            Offset: 0
          Layout:
            X: 0
            Y: 0
            Width: 24
            Height: 32
        - Type: graph
          Title: service graph
          Graph:
            Type: service
            Service: !Ref Service
            Name: some.metric
          Range:
            Type: relative
            Period: 3600
            Offset: 0
          Layout:
            X: 0
            Y: 0
            Width: 24
            Height: 32
        - Type: graph
          Title: service expression
          Graph:
            Type: expression
            Expression: avg(roleSlots("server:role","loadavg5"))
          Range:
            Type: relative
            Period: 3600
            Offset: 0
          Layout:
            X: 0
            Y: 0
            Width: 24
            Height: 32
        - Type: value
          Title: host value
          Metric:
            Type: host
            Host: !Ref Host
            Name: some.metric
          Layout:
            X: 0
            Y: 0
            Width: 24
            Height: 32
        - Type: value
          Title: service value
          Metric:
            Type: service
            Service: !Ref: Service
            Name: some.metric
          Layout:
            X: 0
            Y: 0
            Width: 24
            Height: 32
        - Type: value
          Title: expression value
          Metric:
            Type: expression
            Expression: avg(roleSlots("server:role","loadavg5"))
          Layout:
            X: 0
            Y: 0
            Width: 24
            Height: 32
        - Type: markdown
          Title: markdown
          Markdown: |
            # Some Awesome Service
            - Markdown Text Here
          Layout:
            X: 0
            Y: 0
            Width: 24
            Height: 32
        - Type: alertStatus
          Title: alert status
          Role: !Ref Role
          Layout:
            X: 0
            Y: 0
            Width: 24
            Height: 32

  Downtime:
    Type: Mackerel::Downtime
    Properties:
      Name: test of downtime
      Start: 1573198000
      Duration: 10
      ServiceScopes:
        - !Ref Service
        - !Ref Service
      ServiceExcludeScopes:
        - !Ref Service
        - !Ref Service
      RoleScopes:
        - !Ref Role
        - !Ref Role
      RoleExcludeScopes:
        - !Ref Role
        - !Ref Role
      MonitorScopes:
        - !Ref MonitorConnectivity
      MonitorExcludeScopes:
        - !Ref MonitorHost

  DowntimeWithRecurrence:
    Type: Mackerel::Downtime
    Properties:
      Name: test of downtime
      Start: 1573198000
      Duration: 10
      Recurrence:
        Type: weekly
        Interval: 2
        Weekdays:
          - Sunday
          - Saturday
        Until: 1573198000

  User:
    Type: Mackerel::User
    Properties:
      Email: john.doe@example.com

  # Example for AWS Integrations using IAM Role (recommended)
  AWSIntegrationExternalId:
    Type: Mackerel::AWSIntegrationExternalId
  MackerelRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::217452466226:root
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                "sts:ExternalId": !GetAtt AWSIntegrationExternalId.Id
  AWSIntegration1:
    Type: Mackerel::AWSIntegration
    Properties:
      Name: shogo82148-test
      RoleArn: !GetAtt MackerelRole.Arn
      ExternalId: !Ref AWSIntegrationExternalId
      Region: !Ref AWS::Region
      Services:
        - ServiceId: S3
          Enable: true

  # Example for AWS Integrations using IAM User (deprecated)
  MackerelUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: dashboard-deployment
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Deny
                Action: "*"
                Resource: "*"
  MackerelAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref MackerelUser
  AWSIntegration2:
    Type: Mackerel::AWSIntegration
    Properties:
      Name: shogo82148-test
      Key: !Ref MackerelAccessKey
      SecretKey: !GetAtt MackerelAccessKey.SecretAccessKey
      Region: !Ref AWS::Region
      Services:
        - ServiceId: S3
          Enable: true

Outputs:
  OrgName:
    Value: !GetAtt Org.Name
  ServiceName:
    Value: !GetAtt Service.Name
  RoleName:
    Value: !GetAtt Role.Name
  RoleFullName:
    Value: !GetAtt Role.FullName
  HostName:
    Value: !GetAtt Host.Name
  UserEmail:
    Value: !GetAtt User.Email
