AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: "cfn-mackerel-macro v0.0.6 - provide a CloudFormation macro for creating Mackerel resources."

Metadata:
  AWS::ServerlessRepo::Application:
    Name: cfn-mackerel-macro
    Description: provide a CloudFormation macro for creating Mackerel resources
    Author: Shogo Ichinose
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ["macro", "mackerelio"]
    HomePageUrl: https://github.com/shogo82148/cfn-mackerel-macro
    SemanticVersion: "0.0.6"
    SourceCodeUrl: https://github.com/shogo82148/cfn-mackerel-macro

Parameters:
  ParameterName:
    Type: AWS::SSM::Parameter::Name
    Description: Name of SSM Parameter Store Parameter for the Mackerel API Key.
  LogLevel:
    Type: String
    Default: warning
    AllowedValues: [panic, fatal, error, warn, warning, info, debug, trace]
    Description: log level(panic, fatal, error, warn, warning, info, debug, trace)
  BaseUrl:
    Type: String
    Default: "https://api.mackerelio.com/"
    Description: base url for the Mackerel API

Resources:
  ResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: provided.al2
      CodeUri: ./resource.zip
      Handler: main
      Policies:
        - SSMParameterReadPolicy:
            # HACK: trim "/" prefix. See https://github.com/aws/serverless-application-model/issues/1112
            ParameterName: !Join ["", !Split ["^/", !Sub "^${ParameterName}"]]
      Environment:
        Variables:
          MACKEREL_APIKEY_PARAMETER: !Ref ParameterName
          MACKEREL_APIKEY_WITH_DECRYPT: "1"
          MACKEREL_APIURL: !Ref BaseUrl
          MACKEREL_LOG_LEVEL: !Ref LogLevel
      Tags:
        Version: 0.0.6

  MacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      CodeUri: ./macro.zip
      Handler: app.handler
      Environment:
        Variables:
          LAMBDA_ARN: !GetAtt ResourceFunction.Arn
      Tags:
        Version: 0.0.6

  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: Mackerel
      FunctionName: !GetAtt MacroFunction.Arn
