AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: "cfn-mackerel-macro v%%VERSION%% - provide a CloudFormation macro for creating Mackerel resources."

Parameters: 
  ParameterName: 
    Type: AWS::SSM::Parameter::Name
    Description: Name of SSM Parameter Store Paramer for the Mackerel API Key.
  LogLevel:
    Type: String
    Default: warning
    AllowedValues: [panic, fatal, error, warn, warning, info, debug, trace]
    Description: log level(panic, fatal, error, warn, warning, info, debug, trace)
  BaseUrl:
    Type: String
    Default: "https://api.mackerelio.com/"
    Description: base url for the Mackerel API

Resources:
  ResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      CodeUri: ./resource.zip
      Handler: main
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ParameterName}"
                - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterName}"
      Environment:
        Variables:
          MACKEREL_APIKEY_PARAMETER: !Ref ParameterName
          MACKEREL_APIKEY_WITH_DECRYPT: 1
          MACKEREL_APIURL: !Ref BaseUrl
          FORWARD_LOG_LEVEL: !Ref LogLevel
      Tags:
        Version: %%VERSION%%

  MacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: ./macro.zip
      Handler: app.handler
      Environment:
        Variables:
          LAMBDA_ARN: !GetAtt ResourceFunction.Arn
      Tags:
        Version: %%VERSION%%

  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: Mackerel
      FunctionName: !GetAtt MacroFunction.Arn
