name: test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: |
          make test

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

      - name: cfn-lint
        uses: scottbrenner/cfn-lint-action@master
        with:
          args: --override-spec cfn-resource-specification.json example.yaml
