name: test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: "1.13"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: |
        make test

    - name: cfn-lint
      uses: scottbrenner/cfn-lint-action@master
      with:
        args: --override-spec cfn-resource-specification.json example.yaml
